# Generated by Django 6.0.7 on 2026-07-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Used in the project page URL.', max_length=170, unique=True)),
                ('short_description', models.CharField(help_text='A concise summary for project cards.', max_length=300)),
                ('description', models.TextField(help_text='Full project description.')),
                ('role', models.CharField(blank=True, help_text='Your individual role, especially for group projects.', max_length=200)),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated technologies.', max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/')),
                ('report', models.FileField(blank=True, help_text='Optional PDF report.', null=True, upload_to='projects/reports/')),
                ('repository_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In progress'), ('archived', 'Archived')], default='completed', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Display this project on the homepage.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateField(blank=True, help_text='Approximate project completion or creation date.', null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at', 'title'],
            },
        ),
    ]
