# Generated by Django 6.0.7 on 2026-07-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_description',
            field=models.CharField(blank=True, help_text='Example: YouTube walkthrough, architecture demo, live recording.', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
