# Generated by Django 6.0.7 on 2026-07-30 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Used in the post URL.', max_length=220, unique=True)),
                ('summary', models.CharField(blank=True, help_text='Optional summary shown on the Notes page.', max_length=300)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notes/images/')),
                ('published', models.BooleanField(default=False, help_text='Only published posts are visible publicly.')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
